CREATE TABLE `104hackathon-welfare`.`jobs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `custno` VARCHAR(40) NOT NULL,
  `jobno` INT UNSIGNED NULL,
  `job` TEXT NULL,
  `jobcat1` INT NULL,
  `jobcat2` INT NULL,
  `jobcat3` INT NULL,
  `edu` TINYINT UNSIGNED NULL COMMENT '最高學歷(用二進位儲存)(1: 高中以下 2:高中4:專科 8:大學16碩士 32:博士)b',
  `salary_low` INT UNSIGNED NULL,
  `salary_high` INT UNSIGNED NULL,
  `role` TINYINT UNSIGNED NULL COMMENT '1:全職2:兼職 3:高階4:殘障+全 5:殘障+兼 6:殘障+高',
  `language1` MEDIUMINT UNSIGNED NULL,
  `language2` MEDIUMINT UNSIGNED NULL,
  `language3` MEDIUMINT UNSIGNED NULL,
  `work_dur` INT NULL COMMENT 'working duration 年資/工作經驗',
  `major_cat1` INT UNSIGNED NULL,
  `major_cat2` INT UNSIGNED NULL,
  `major_cat3` INT UNSIGNED NULL,
  `industry` INT UNSIGNED NULL,
  `vacation` VARCHAR(20) NULL COMMENT 'wrok time 休假制度',
  `role_status` TINYINT UNSIGNED NULL COMMENT '1:上班族 2:應屆畢 4:日間部 8:夜間部 16:尋找國防役 32:外籍人士 64:原住民 128:接受人力派遺-派遺單位專用 256:二度就業-派遺單位專用 512:soho',
  `management` TINYINT NULL COMMENT '管理責任：-1:該職務尚未填寫 0:無 1:4人以下 2:5-8人 3:9-12人 4:13人以上 5:未定',
  `buiness_trip` TINYINT NULL COMMENT '是否出差：-1:該職務尚未填寫 0:無 1:1個月內 2:3個月以下 3:6個月以下 4:7個月以上 5:未定 (註.3)',
  `addr_no` INT UNSIGNED NULL,
  `work_time` TINYINT NULL COMMENT '上班時段：0:預設 1:日班 2:晚班 4:大夜班 8:假日班',
  `need_emp_low` INT UNSIGNED NULL COMMENT '最低需求人數',
  `need_emp_high` INT UNSIGNED NULL COMMENT '最高需求人數',
  `startby` TINYINT UNSIGNED NULL COMMENT '上班日期：0:一週內 1:兩週 2:一個月 3:不限 4:可年後上班',
  `exp_jobcat1` INT UNSIGNED NULL,
  `exp_jobcat2` INT UNSIGNED NULL,
  `exp_jobcat3` INT UNSIGNED NULL,
  `desc` TEXT NULL,
  `others` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
